name: Bug Report
description: Report a bug in one of the Jamaica Developer Kit packages
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug. Please fill out the fields below so we can diagnose and fix the issue as quickly as possible.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
      placeholder: Describe what went wrong.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: The minimal steps needed to reproduce the behavior.
      placeholder: |
        1. Install package with `pnpm add jamaica-trn`
        2. Call `validateTRN('...')`
        3. Observe the error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
      placeholder: Describe the expected outcome.
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened instead.
      placeholder: Describe what happened, including any error messages or stack traces.
    validations:
      required: true

  - type: dropdown
    id: package
    attributes:
      label: Package Affected
      description: Which package is this bug related to?
      options:
        - jamaica-trn
        - jamaica-phone
        - jamaica-addresses
        - jamaica-constants
        - jamaica-currency
        - jamaica-tax
        - jamaica-banks
        - jamaica-gov-fees
        - jamaica-parishes
        - jamaica-places
        - jamaica-constituencies
        - jamaica-transport
        - jamaica-schools
        - jamaica-health
        - jamaica-emergency
        - jamaica-holidays
        - jamaica-zod
        - jamaica-react
        - jamaica-express
        - jamaica-boj
        - jamaica-open-data
        - jamaica-cli
        - jamaica (meta)
        - Other
    validations:
      required: true

  - type: dropdown
    id: language
    attributes:
      label: Language
      description: Which language implementation is affected?
      options:
        - TypeScript
        - Python
        - Both
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: The version of the package where the bug occurs.
      placeholder: e.g. 1.2.3
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Any relevant environment details.
      placeholder: |
        - OS: macOS 14.2
        - Node.js: 22.1.0
        - Python: 3.12.1
        - Package manager: pnpm 9.5.0
    validations:
      required: false
