blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/itsanderz/jamaica-dev-kit/issues
    about: Ask questions, share ideas, or discuss the project with the community.
